### ISSUE TITLE
Contactar para CoP: Grupos de Sevilla

### ISSUE THREAD

**Issue by opensouthcode** [opensouthcode/2019#2]
Usando la plantilla mensaje_CoP.txt de este repo, enviar un mensaje a los grupos y comunidades afines a las tecnologías libre/open source de Sevilla:

- [x] Sevilla Java User Group: https://www.meetup.com/SVQJUG/
- [x] Geoinquietos: http://geoinquietos.org/grupos/sevilla/
- [x] PHPSevilla: https://www.meetup.com/PHP-Sevilla/
- [x] OWASP Sevilla https://www.owasp.org/index.php/Sevilla
- [ ] Docker Sevilla https://www.meetup.com/Docker-Sevilla/
- [x] Sevilla R-Users https://www.meetup.com/Sevilla-R-users/
- [x] Python Sevilla: https://www.meetup.com/Python-Sevilla/
- [ ] Wordpress: https://www.meetup.com/WordPress-Sevilla/
- [ ] GDG Sevilla: https://www.meetup.com/GDGSevilla/
- [ ] SevillaQA: https://www.meetup.com/SevillaQA/
- [x] Sevilla Typescript: https://www.meetup.com/Sevilla-TypeScript/

**Comment by javilinux** [comment]
Mail enviado a:

- Sevilla Java User Group
- geoinquietos
-  PHPSevilla
- OWASP Sevilla
