### ISSUE TITLE
Realizar cartel de la conferencia

### ISSUE THREAD

**Issue by opensouthcode** [opensouthcode/2019#4]
Realizar cartel informativo de la conferencia. 

Los datos a mostrar serán: 

**Opensouthcode 2019** 

Conferencia de software libre y tecnologías abiertas

24 y 25 de Mayo 2019. Polo digital de Málaga

Entrada gratuita

https://www.opensouthcode.org

**Comment by davidsf** [comment]
* Añadido el logo de OSC al repo: https://github.com/opensouthcode/2019/blob/master/logo_osc.svg
* Fecha: cuando puedas. Ahora mismo no iría a imprenta ya que habrá que esperar un poco a los patrocinadores que consigamos.
* Formato: Sí, A3 está bien
* Sí, tenemos redes sociales, sobre todo comunicamos por twitter. Tambien usamos el blog.

Gracias Victor!

**Comment by necromic** [comment]
Ok!

Actualizo con un cartel, si tenemos Ok hago el arte final. La franja blanca de abajo es para los patrocinadores, colaboradores, etc... si es necesario ponerlos.

Necesitaría esos logos en caso de hacer falta.

![Opensouthcode19_v1](https://user-images.githubusercontent.com/26384554/54496517-91fae280-48f0-11e9-9751-d0b103784ccc.png)

**Comment by necromic** [comment]
Cambios hechos :v:

![opensouthcode19_v2](https://user-images.githubusercontent.com/26384554/54557657-fdf64d00-49bb-11e9-8fd2-5aafcb6dc512.png)

**Comment by opensouthcode** [comment]
Patrocina: Accenture y Ayesa. Logos en: https://github.com/opensouthcode/2019/tree/master/logos

Colabora: Polo Digital

**Comment by necromic** [comment]
Done! Añadido el `¡` que faltaba.

![opensouthcode19](https://user-images.githubusercontent.com/26384554/54878269-9e1ffc00-4e2a-11e9-8bf8-bd15a21f4d4f.png)

**Comment by necromic** [comment]
Te lo dejo por aquí @davidsf comprimido el arte final del cartel, van dos PDFs uno con sangrado y marcas de corte y otro sin. Por si fuese necesario.

[AF_OpenSouthCode19.zip](https://github.com/opensouthcode/2019/files/3019909/AF_OpenSouthCode19.zip)
