### ISSUE TITLE
Descuento Renfe

### ISSUE THREAD

**Issue by opensouthcode** [opensouthcode/2019#6]
Renfe tiene descuentos para viajes a eventos y conferencias. Ver como funciona el sistema para poder ofrecerlo a los visitantes.

**Comment by demcorp** [comment]
Enviada solicitud a Renfe, hay que esperar respuesta.

**Comment by opensouthcode** [comment]
Nos han contestado y se les ha enviado el logo. Esperando confirmación definitiva.

**Comment by opensouthcode** [comment]
Confirmado que se puede realizar, pero hay que hacerlo de forma personalizada, no se puede colgar en la web.

¿habilitamos un email y se le envía la info?

**Comment by demcorp** [comment]
Pues sí, se publicita en la web y en twitter (u otros medios) que es necesario escribir a esa dirección para pedir el descuento. Yo podría encargarme de recepcionar el correo y enviar la información necesaria.

**Comment by opensouthcode** [comment]
Se publicó ayer en blog y twitter. Email renfe@opensouthcode.org reenviado a @davidsf y @demcorp
